// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwapSmart.Data;

#nullable disable

namespace SwapSmart.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119000002_AddTradeOffers")]
    partial class AddTradeOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SwapSmart.Models.TradeOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContactOpened")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfferedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OfferedItemId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("RequestedItemId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("TradeOffers", (string)null);
                });

            modelBuilder.Entity("SwapSmart.Models.TradeOffer", b =>
                {
                    b.HasOne("SwapSmart.Models.Item", "OfferedItem")
                        .WithMany()
                        .HasForeignKey("OfferedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwapSmart.Models.Item", "RequestedItem")
                        .WithMany()
                        .HasForeignKey("RequestedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwapSmart.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapSmart.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferedItem");

                    b.Navigation("Receiver");

                    b.Navigation("RequestedItem");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
